dist: trusty
sudo: required
language: python
notifications:
  slack:
    on_success: never
    on_failure : never
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
env:
  - PARI_VERSION=pari-2.9.4
    URLDIR=OLD/2.9
  - PARI_VERSION=pari-2.9.5
    URLDIR=OLD/2.9
  - PARI_VERSION=pari-2.11.0
    URLDIR=unix
  - PARI_VERSION=pari-2.11.1
    URLDIR=unix
  - PARI_VERSION=pari-2.10.1.beta
    URLDIR=unstable
  - PARI_VERSION=snapshot
    URLDIR=snapshots

before_install:
  - export LC_ALL=C  # Test that this doesn't break Unicode
  - export PATH="/usr/lib/ccache:$PATH"
  - ccache -M 256M && ccache -s
install:
  - bash -x .travis-install-pari.sh
  - pip install --build=/tmp/pip --verbose -r requirements.txt
  # CFLAGS:
  # -O1 to speed up compilation (compared to -O2 or -O3)
  # -fno-strict-aliasing because that is the default in Python
  # -fno-tree-copyrename works around http://gcc.gnu.org/bugzilla/show_bug.cgi?id=56982
  # -Wall -Werror to check for potential bugs
  # -Wno-unused to remove false positive errors
  - env CFLAGS="-O1 -fno-strict-aliasing -fno-tree-copyrename -Wall -Wno-unused -Werror" pip install --verbose .
# command to run tests
script:
  - make check
  - (cd docs && make html)
cache:
  directories:
    - $HOME/.ccache
